In [1]:
# This cell does not get executed when run with Times Square
import os
import datetime

visit_origin = os.environ.get("SCHEDVIEW_VISIT_ORIGIN", "baseline")
day_obs = int(
    os.environ.get(
        "SCHEDVIEW_DAY_OBS",
        (
            (datetime.date.today() - datetime.timedelta(days=1)).isoformat()
            if visit_origin in ("lsstcam", "latiss", "lsstcomcam")
            else "2026-12-21"
        ),
    ).replace("-", "")
)

In [2]:
import os
import sys

#sched_source = 'env'
sched_source = 'shared'
#sched_source = 'devel'
match sched_source:
    case 'shared':
        if os.path.exists('/sdf/data/rubin/shared/scheduler/packages'):
            sys.path.insert(0, "/sdf/data/rubin/shared/scheduler/packages/uranography-1.2.1")
            sys.path.insert(0, "/sdf/data/rubin/shared/scheduler/packages/rubin_scheduler-3.11.0")
            sys.path.insert(0, "/sdf/data/rubin/shared/scheduler/packages/rubin_sim-2.2.4")
            sys.path.insert(0, "/sdf/data/rubin/shared/scheduler/packages/schedview-0.18.1.dev11+g045227b")
    case 'devel':
        if os.path.exists('/sdf/data/rubin/user/neilsen/devel'):
            sys.path.insert(0, "/sdf/data/rubin/user/neilsen/devel/rubin_scheduler")
            sys.path.insert(0, "/sdf/data/rubin/user/neilsen/devel/rubin_sim")
            sys.path.insert(0, "/sdf/data/rubin/user/neilsen/devel/schedview")
    case _:
        # Use whatever is in the kernel python environment
        pass

In [3]:
from schedview.util import config_logging_for_reports
import logging
config_logging_for_reports(logging.ERROR)

In [4]:
import datetime
import os
import sqlite3
import sys
from collections import defaultdict
from pathlib import Path

import astropy
import astropy.units as u
import bokeh
import bokeh.io
import bokeh.layouts
import bokeh.models
import bokeh.plotting
import bokeh.transform
import cartopy
import colorcet
import healpy
import healpy as hp
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from erfa import ErfaWarning
from astropy.coordinates import SkyCoord, get_body
from astropy.time import Time
from astropy.visualization import ZScaleInterval
from IPython.display import HTML, display, Markdown, HTML
from lsst.resources import ResourcePath

In [5]:
usdf_sim_data_dir = "/sdf/data/rubin/shared/rubin_sim_data"
if os.path.exists(usdf_sim_data_dir):
    os.environ["RUBIN_SIM_DATA_DIR"] = "/sdf/data/rubin/shared/rubin_sim_data"

In [6]:
import schedview.collect.consdb
import schedview.collect.nightreport
import schedview.collect.timeline
import rubin_scheduler
import rubin_scheduler.site_models
import rubin_scheduler.utils
import schedview.compute.astro
import schedview.compute.visits
import schedview.compute.nightreport
import schedview.plot.survey_skyproj
import schedview.plot.visitmap
import schedview.plot.nightreport
import schedview.collect.visits
import rubin_sim.sim_archive
import uranography
from rubin_sim.data import get_baseline
from rubin_scheduler.scheduler.model_observatory import ModelObservatory
from rubin_sim import maf
from schedview.compute.camera import LsstCameraFootprintPerimeter
from uranography.api import Planisphere, make_zscale_linear_cmap
from schedview import DayObs
from rubin_scheduler.utils.consdb import KNOWN_INSTRUMENTS

In [7]:
if not Path('/sdf/group/rubin/web_data/sim-data').exists():
    schedview.collect.visits.OPSIMDB_TEMPLATE = str(
        Path.home().joinpath("Data/sim-data/sims_featureScheduler_runs{sim_version}/baseline/baseline_v{sim_version}_10yrs.db")
    )

In [8]:
# Validate the input
import re

assert visit_origin in KNOWN_INSTRUMENTS or visit_origin == 'baseline' or re.match(r"^\d+\.\d+$", visit_origin) is not None

In [9]:
# Degraded IERS accuracy is never going to be important for these figures.

# If IERS degraded accuracy encountered, don't fail, just keep going.
astropy.utils.iers.conf.iers_degraded_accuracy = "ignore"

In [10]:
bokeh.io.output_notebook(hide_banner=True)

In [11]:
%matplotlib inline

In [12]:
ORIGIN_TELESCOPE = defaultdict(
    np.array(['Simonyi']).item,
    {'latiss': 'AuxTel'}
)

In [13]:
observatory = ModelObservatory(init_load_length=1)
timezone = "Chile/Continental"
telescope = ORIGIN_TELESCOPE[visit_origin]
from_opsim = visit_origin not in KNOWN_INSTRUMENTS
use_matplotlib = True
science_programs_to_include = ['BLOCK-365']
telescope = "AuxTel" if visit_origin.lower()=="latiss" else "Simonyi"

In [14]:
if from_opsim:
    display(Markdown(f"# Scheduler-oriented night summary of {day_obs} from baseline {visit_origin}"))
else:
    display(Markdown(f"# Scheduler-oriented night summary of {visit_origin} on {day_obs}"))

# Scheduler-oriented night summary of 20261221 from baseline baseline

This report is a summary of a night of observing designed to understand scheduler behavior during the night, identify scheduler problems, and otherwise monitor scheduler performance.

In [15]:
day_obs = DayObs.from_date(day_obs)
observatory.mjd = day_obs.mjd + 1 - observatory.location.lon.deg/360 ;# The approximate middle of the night

In [16]:
visits = schedview.collect.visits.read_visits(day_obs, visit_origin, stackers = schedview.collect.visits.NIGHT_STACKERS)

In [17]:
if not from_opsim:
    if visit_origin == 'lsstcam':
        visits = visits.loc[visits['science_program'].isin(science_programs_to_include), :]

    night_reports = schedview.collect.nightreport.get_night_report(day_obs, telescope)
    best_version_of_night_report =  schedview.compute.nightreport.best_night_report(night_reports)
    night_report_markdown = schedview.plot.nightreport.night_report_markdown(best_version_of_night_report)
    display(Markdown(night_report_markdown))

## Sun and Moon

### Events

In [18]:
night_events = schedview.compute.astro.night_events(day_obs.date)
night_events

,MJD,LST,UTC,Chile/Continental
event,,,,
sunset,61395.986013,14.770092,2026-12-21 23:39:51.552000+00:00,2026-12-21 20:39:51.552000-03:00
sun_n12_setting,61396.031483,31.184022,2026-12-22 00:45:20.138000+00:00,2026-12-21 21:45:20.138000-03:00
sun_n18_setting,61396.056464,40.201615,2026-12-22 01:21:18.451000+00:00,2026-12-21 22:21:18.451000-03:00
sun_n18_rising,61396.334381,140.525803,2026-12-22 08:01:30.510000+00:00,2026-12-22 05:01:30.510000-03:00
sun_n12_rising,61396.359364,149.544484,2026-12-22 08:37:29.084000+00:00,2026-12-22 05:37:29.084000-03:00
sunrise,61396.404832,165.957467,2026-12-22 09:42:57.443000+00:00,2026-12-22 06:42:57.443000-03:00
moonrise,61396.948739,2.300256,2026-12-22 22:46:11.042000+00:00,2026-12-22 19:46:11.042000-03:00
moonset,61396.318680,134.857990,2026-12-22 07:38:53.950000+00:00,2026-12-22 04:38:53.950000-03:00
night_middle,61396.195422,90.363779,2026-12-22 04:41:24.498000+00:00,2026-12-22 01:41:24.498000-03:00

Modified Julian Date (MJD) is in units of days (UTC).

Local Sidereal Time (LST) is in units of degrees.

In [19]:
# Refine the mjd of the middle of the night, unlikely to be important.
observatory.mjd = night_events.loc["night_middle", "MJD"]

### Positions at local solar midnight

In [20]:
body_positions = schedview.compute.astro.compute_sun_moon_positions(observatory)
body_positions

coordinate          RA        dec        alt          az      phase
sun         269.949410 -23.435547 -36.316272  179.965007        NaN
moon         59.938236  26.546510  26.291084  330.083604  84.824019

RA, dec, alt, and az are all in units of degrees.

## Conditions and statistics

### Numbers of exposures, and gaps between them

In [21]:
if len(visits):
    sv_summary = schedview.compute.visits.compute_sv_summary(visits, night_events.loc["sun_n12_setting", "MJD"],
        night_events.loc["sunrise", "MJD"])

    sv_table = schedview.plot.create_sv_summary_table(sv_summary)
    display(HTML(sv_table))
else:
    print("No visits")

In [22]:
if len(visits):
    overhead_summary = schedview.compute.visits.compute_overhead_summary(
        visits,
        night_events.loc["sun_n12_setting", "MJD"],
        night_events.loc["sun_n12_rising", "MJD"],
    )
    summary_table = schedview.plot.create_overhead_summary_table(overhead_summary)
    display(HTML(summary_table))
else:
    print("No visits")

## Value timelines

Select a value to plot in the subplot on the right using the dropdown at the top of that subplot.

In [23]:
if from_opsim:
    if len(visits):
        fig = schedview.plot.plot_visit_param_vs_time(visits, 'airmass', show_column_selector=True)
        bokeh.io.show(fig)
    else:
        print("No visits")
else:
    user_param_plot_kwargs = {}

    timeline_data = await schedview.collect.timeline.collect_timeline_data(
            day_obs,
            sal_indexes=schedview.collect.SAL_INDEX_GUESSES[visit_origin],
            telescope=telescope,
            log_messages=False,
            scheduler_dependencies=True,
            scheduler_configuration=True,
            scheduler_snapshots=True,
            block_status=False,
        )
    timeline_data["model_sky"] = schedview.compute.astro.get_median_model_sky(day_obs)
    timeline_data['sun'] = night_events

    try:
        nominal_visits = rubin_sim.sim_archive.sim_archive.fetch_latest_prenight_sim_for_nights(
            str(day_obs),
            str(day_obs),
            max_simulation_age=1 + Time.now().mjd - day_obs.mjd,
            stackers=schedview.collect.visits.NIGHT_STACKERS,
            telescope=telescope,
        )
    except:
        nominal_visits = None

    if nominal_visits is not None:
        nominal_visits = nominal_visits.loc[(nominal_visits.observationStartMJD > day_obs.start.mjd) & (nominal_visits.observationStartMJD < day_obs.end.mjd), :]

    if nominal_visits is not None and len(nominal_visits)>0:
        timeline_data['visits'] = pd.concat([
            visits.assign(label='Completed'),
            nominal_visits.assign(
                label='Nominal',
            )
        ])
        user_param_plot_kwargs['marker_transform'] = bokeh.models.CategoricalMarkerMapper(factors=['Nominal', 'Completed'], markers=['circle', 'asterisk'])
    else:
        timeline_data['visits'] = visits
    
    p = schedview.plot.make_timeline_scatterplots(user_param_plot_kwargs=user_param_plot_kwargs, **timeline_data)
    bokeh.io.show(p)

## Visit map

In [24]:
if len(visits):
    visits = schedview.compute.visits.add_coords_tuple(visits)
    vmap, vmap_data = schedview.plot.visitmap.create_visit_skymaps(
        visits=visits,
        night_date=day_obs.date,
        timezone=timezone,
        observatory=observatory,
    )
    bokeh.io.show(vmap)
else:
    print("No visits")

The above plots show the visits collected during the night in two different representations, modeled after physical observing tools.

 - The "Armillary sphere" shows the sphere in orthographic projection, with the center point of the projection controlled by the "center alt" and "center az" sliders beneath the plot. A static orthogrophic projection is not an equal-area projection, but playing with the sliders is a helpful way to inform a human's spatial reasoning in three dimensions.
 - The "Planisphere" shows the sky in [Lambert Azimuthal Equal Area Projection](https://en.wikipedia.org/wiki/Lambert_azimuthal_equal-area_projection), centered at the south celestial pole, with R.A. increasing counterclockwise. The projection used is equal area, but highly distorted near the north celestial pole (outside the LSST footprint). This is a particularly helpful representation for planning observing, because changes in time in relevant features are simple rotations, without alterations in distortion, and there are no discontinuities anywhere in the footprint at any time of year.

Both plots show the footprints of camera pointing taken up to the time set by the MJD slider, with the most recent three pointings outlined in cyan. The fill colors are set according to the [descolors palette](https://github.com/DarkEnergySurvey/descolors):

 - <span style='background-color:#56b4e9'>&nbsp;&nbsp;&nbsp;</span><span style='color:#56b4e9'> blue</span>: u band
 - <span style='background-color:#008060'>&nbsp;&nbsp;&nbsp;</span><span style='color:#008060'> green</span>: g band
 - <span style='background-color:#ff4000'>&nbsp;&nbsp;&nbsp;</span><span style='color:#ff4000'> red</span>: r band
 - <span style='background-color:#850000'>&nbsp;&nbsp;&nbsp;</span><span style='color:#850000'> brown/crimson</span>: i band
 - <span style='background-color:#6600cc'>&nbsp;&nbsp;&nbsp;</span><span style='color:#6600cc'> purple</span>: z band
 - <span style='background-color:#000000'>&nbsp;&nbsp;&nbsp;</span><span style='color:#000000'> black</span>: y band

Both plots have the following additional annotations:
 - The gray background shows the planned final depth of the LSST survey.
 - The orange disk shows the coordinates of the moon.
 - The yellow disk shows the coordinates of the sun.
 - The green line (oval) shows the ecliptic.
   - The sun moves along the ecliptic in the direction of increasing R.A. (counter-clockwise in the planisphere figure) such that it makes a full revolution in one year.
   - The moon moves roughly (within 5.14°) along the ecliptic in the direction of increasing R.A. (counter-clockwise in the planisphere figure) , completing a full revolution in one [sidereal month](https://en.wikipedia.org/wiki/Lunar_month#Sidereal_month) (a bit over 27 days), about 14° per day.
 - The blue line (oval) shows the plane of the Milky Way.
 - The black line shows the horizon at the time set by the MJD slider.
 - The red line shows a zenith distince of 70° (airmass=2.9) at the time set by the MJD slider.

## Survey Progress

### Map numbers of visits accumulated so far

In [25]:
conditions = observatory.return_conditions()

In [26]:
previous_day_obs = DayObs.from_date(day_obs.mjd-1, int_format='mjd')
previous_visits = schedview.collect.visits.read_visits(previous_day_obs, visit_origin, stackers = schedview.collect.visits.NIGHT_STACKERS, num_nights=10000)
if not from_opsim:
    previous_visits = previous_visits.loc[previous_visits['science_program'].isin(science_programs_to_include), :]

In [ ]:
if len(visits) and len(previous_visits) \
        and not np.all(np.isnan(visits['fiveSigmaDepth'])) \
        and not np.all(np.isnan(previous_visits['fiveSigmaDepth'])):
    fig = schedview.plot.survey.create_metric_visit_map_grid(
        maf.CountMetric(col='fiveSigmaDepth', metric_name="Numbers of visits"),
        previous_visits.loc[np.isfinite(previous_visits['fiveSigmaDepth']), :],
        visits.loc[np.isfinite(visits['fiveSigmaDepth']), :],
        observatory,
        nside=32,
        use_matplotlib=use_matplotlib
    )

Each subplot represents the progress in the survey in a different filter, presented in a [Lambert Azimuthal Equal Area Projection](https://en.wikipedia.org/wiki/Lambert_azimuthal_equal-area_projection), centered at the south celestial pole.

Annotations are similar to those of the "Visit Map" above:

 - Black outlines show the camera footprint of each exposure taken on this night.
 - The blue backdrop represents the accumulated effective exposure time, t<sub>eff</sub> (as defined above) at the start of the night.
 - The orange disk shows the coordinates of the moon.
 - The yellow disk shows the coordinates of the sun.
 - The green line (oval) shows the ecliptic.
 - The blue line (oval) shows the plane of the Milky Way.
 - Broken red ovals show a zenith distince of 70° (airmass=2.9) at morning and evening 12° twilight.
   - The dashed portions of each red oval show the extent of what is observable at all during the night.
   - As time progress through the night, the ZD circle maintains its shape, moving counter-clockwise around the pole over the course of the night.

### Map the most recent visit so far

In [ ]:
if len(previous_visits):
    fig = schedview.plot.survey.create_metric_visit_map_grid(
        maf.AgeMetric(night_events.loc['sunset', 'MJD']),
        previous_visits,
        visits,
        observatory,
        nside=32,
        use_matplotlib=use_matplotlib,
        vmin=0,
        vmax=10,
        cmap=colorcet.cm.blues_r
    )

Each subplot represents the time since the most recent visits to each point in the sky, by filter, presented in a Lambert Azimuthal Equal Area Projection, centered at the south celestial pole.

Parts of the sky visited most recently are dark blue, growing fainter and grayer for areas visited less recently. Regions not visited in the last 10 days are not colored.

Other features and annotations are the same as those of the depth map, above.

## DDF Cadence

In [ ]:
time_window_duration=90

In [ ]:
try:
    ddf_visits = schedview.collect.visits.read_ddf_visits(day_obs, visit_origin, num_nights=time_window_duration)
    if not from_opsim:
        ddf_visits = ddf_visits.loc[ddf_visits['science_program'].isin(science_programs_to_include), :]
except:
    ddf_visits = []

In [ ]:
if len(ddf_visits):
    nightly_ddf = schedview.compute.visits.accum_stats_by_target_band_night(ddf_visits, target_column='field_name')
    cadence_plots = schedview.plot.create_cadence_plot(
        nightly_ddf, day_obs.mjd - time_window_duration, day_obs.mjd, target_column='field_name'
    )
    bokeh.io.show(cadence_plots)
else:
    print("No DDF visits")

The y-axis (height of the vertical bars) represents the accumulated effective exposure time, t<sub>eff</sub> (as defined above) accumulated over all exposures on the field for the night, colored by filter.

## Histogram of gaps between exposures

In [ ]:
if len(visits):
    try:
        p1 = schedview.plot.create_overhead_histogram(visits)
        p2 = schedview.plot.plot_overhead_vs_slew_distance(visits)
        overhead_plots = bokeh.layouts.row([p1, p2])
        bokeh.io.show(overhead_plots)
    except Exception as e:
        print(e)
else:
    print("No visits")

"Overhead" is the time window (in seconds) between the end of the previous exposure and the end of the current exposure, minus the exposure time.

## Long gaps between exposures

In [ ]:
if len(visits):
    try:
        for time_column in 'obs_start', 'start_timestamp', 'observationStartDatetime64':
            if time_column in visits:
                break
        num_gaps = 10
        visits["previous_band"] = visits["band"].shift(1)
        long_gap_visits = (
            visits.sort_values("overhead", ascending=False)
            .query("overhead>30")
            .loc[:, [time_column, "overhead", "slewDistance", "band", "previous_band"]]
            .sort_values(time_column)
        )
        display(long_gap_visits)
    except Exception as e:
        print(e)
else:
    print("No visits")

These are the longest gaps between exposures that occur on the night, ordered by duration of the gaps.

Slew time and previous and current filters are noted, because filter changes are the greatest expected contributions to overhead.

## Table of exposures

In [ ]:
# The bokeh table widget and the Rubin RSP notebooks do not work together.
# If running on the Rubin RSP notebook aspect, set on_rsp=True.
# Otherwise, leave it as False
on_rsp = False

In [ ]:
if len(visits):
    for time_column in 'obs_start', 'observationStartDatetime64':
        if time_column in visits:
            break
    displayed_columns_maybe = [
        time_column,
        "fieldRA",
        "fieldDec",
        "band" if "band" in visits else "filter",
        "visitExposureTime",
        "fiveSigmaDepth",
        "eff_time_median",
        "skyBrightness",
        "seeingFwhmEff",
        "target_name",
        "observation_reason",
    ]
    displayed_columns = [c for c in displayed_columns_maybe if c in visits.columns]
    if on_rsp:
        with pd.option_context('display.max_rows', 2000):
            display(visits.loc[:,displayed_columns])
    else:
        schedview.plot.create_visit_table(visits, visible_column_names=displayed_columns, width=1024)
else:
    print("No visits")